# Generated by Django 5.1.4 on 2025-08-24 06:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Original Price ($)')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discounted Price ($)')),
                ('discount_rate', models.IntegerField(blank=True, help_text='A number between 0 and 100.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Rate (%)')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated list of tags (e.g., women, shoes, sale).', max_length=255, verbose_name='Tags')),
                ('features', models.TextField(blank=True, help_text='A detailed description or list of product features.', verbose_name='Features')),
                ('colors', models.CharField(blank=True, help_text='Comma-separated list of available colors.', max_length=255, verbose_name='Available Colors')),
                ('materials', models.CharField(blank=True, max_length=255, verbose_name='Materials')),
                ('measurements', models.CharField(blank=True, max_length=255, verbose_name='Measurements')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='In Stock')),
                ('delivery_availability', models.TextField(blank=True, help_text='Information about delivery options and timing.', verbose_name='Delivery Availability')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product')),
            ],
        ),
    ]
