# Generated by Django 5.1.4 on 2025-08-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_rate',
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, choices=[('almirah', 'Almirah'), ('beds', 'Beds'), ('chairs', 'Chairs'), ('dining', 'Dining'), ('mattress', 'Mattress'), ('sofa', 'Sofa'), ('table', 'Table'), ('safe', 'Safe')], max_length=50, verbose_name='Tag'),
        ),
    ]
