# Generated by Django 5.1.4 on 2025-09-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_discount_rate_alter_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(help_text='Enter the color name', max_length=255, verbose_name='Color for a product')),
                ('image', models.ImageField(upload_to='color_image/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discounted Price (₹)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Original Price (₹)'),
        ),
    ]
