# Generated by Django 5.1.4 on 2025-09-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_color_alter_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(help_text='Enter the color name', max_length=255, verbose_name='Color for a product'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='app.color', verbose_name='Available Colors'),
        ),
    ]
