# Generated by Django 5.1.4 on 2025-09-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_color_color_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color',
        ),
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(default='white', max_length=255, verbose_name='Color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='color_image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='app.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_availability',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurements',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, choices=[('almirah', 'Almirah'), ('beds', 'Beds'), ('chairs', 'Chairs'), ('dining', 'Dining'), ('mattress', 'Mattress'), ('sofa', 'Sofa'), ('table', 'Table'), ('safe', 'Safe')], max_length=50),
        ),
    ]
