# Generated by Django 5.1.4 on 2025-09-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_color_color_color_name_alter_color_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('offers', 'Offers'), ('new_arrivals', 'New Arrivals'), ('best_sellers', 'Best Sellers')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('almirah', 'Almirah'), ('beds', 'Beds'), ('chairs', 'Chairs'), ('dining', 'Dining'), ('mattress', 'Mattress'), ('sofa', 'Sofa'), ('table', 'Table'), ('safe', 'Safe')], max_length=50),
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='color/'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='app.producttag'),
        ),
    ]
