# Generated by Django 5.1.4 on 2025-09-07 17:56

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_producttag_product_category_alter_color_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('offers', 'Offers'), ('new_arrivals', 'New Arrivals'), ('best_sellers', 'Best Sellers')], max_length=32),
        ),
    ]
